import StyleDictionary from 'style-dictionary';
import { promises as fs } from 'fs';

// --- Build shared + non-color tokens (typography, spacing, radii, shadows) ---
const sharedSd = new StyleDictionary({
  source: [
    'tokens/color.shared.json',
    'tokens/typography.json',
    'tokens/spacing.json',
    'tokens/radii.json',
    'tokens/shadows.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.shared.css',
          format: 'css/variables',
          options: { selector: ':root' },
        },
      ],
    },
  },
});

// --- Build light mode colors (default :root) ---
const lightSd = new StyleDictionary({
  source: ['tokens/color.light.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.light.css',
          format: 'css/variables',
          options: { selector: ':root' },
        },
      ],
    },
  },
});

// --- Build dark mode colors ([data-theme="dark"] override) ---
const darkSd = new StyleDictionary({
  source: ['tokens/color.dark.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.dark.css',
          format: 'css/variables',
          options: { selector: '[data-theme="dark"]' },
        },
      ],
    },
  },
});

await sharedSd.buildAllPlatforms();
await lightSd.buildAllPlatforms();
await darkSd.buildAllPlatforms();

// --- Merge into single tokens.css ---
const shared = await fs.readFile('dist/tokens.shared.css', 'utf8');
const light  = await fs.readFile('dist/tokens.light.css',  'utf8');
const dark   = await fs.readFile('dist/tokens.dark.css',   'utf8');

// Rename color-light-* and color-dark-* prefixes to color-* for clean consumer names
const cleanLight = light.replace(/--color-light-/g, '--color-');
const cleanDark  = dark.replace(/--color-dark-/g,  '--color-');

const merged = [
  '/* Babylon Design Tokens — generated by babylon-tokens */',
  '/* DO NOT EDIT — run npm run build to regenerate */',
  '',
  cleanLight,
  '',
  cleanDark,
  '',
  shared,
].join('\n');

await fs.writeFile('dist/tokens.css', merged);

// Clean up intermediate files
await fs.unlink('dist/tokens.shared.css');
await fs.unlink('dist/tokens.light.css');
await fs.unlink('dist/tokens.dark.css');

// --- Generate Tailwind config extension ---
const tailwindTokens = {
  colors: {
    accent:         'var(--color-accent)',
    'accent-hover': 'var(--color-accent-hover)',
    gain:           'var(--color-gain)',
    loss:           'var(--color-loss)',
    warning:        'var(--color-warning)',
    info:           'var(--color-info)',
    bg: {
      base:     'var(--color-bg-base)',
      surface:  'var(--color-bg-surface)',
      elevated: 'var(--color-bg-elevated)',
    },
    text: {
      primary:   'var(--color-text-primary)',
      secondary: 'var(--color-text-secondary)',
      muted:     'var(--color-text-muted)',
      ghost:     'var(--color-text-ghost)',
    },
    border: {
      DEFAULT: 'var(--color-border)',
      strong:  'var(--color-border-strong)',
    },
  },
  fontFamily: {
    sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
    mono: ['JetBrains Mono', 'Courier New', 'monospace'],
  },
  spacing: {
    '1':  '4px',
    '2':  '8px',
    '3':  '12px',
    '4':  '16px',
    '6':  '24px',
    '8':  '32px',
    '12': '48px',
    '16': '64px',
  },
  borderRadius: {
    xs:   '2px',
    sm:   '4px',
    md:   '6px',
    lg:   '10px',
    full: '9999px',
  },
  boxShadow: {
    sm:    '0 1px 3px rgba(0,0,0,0.4)',
    card:  '0 4px 16px rgba(0,0,0,0.5)',
    modal: '0 8px 32px rgba(0,0,0,0.6)',
    focus: '0 0 0 1.5px #7B2FBE',
  },
};

await fs.mkdir('dist', { recursive: true });
await fs.writeFile(
  'dist/tailwind.tokens.js',
  `// Babylon Design Tokens — generated by babylon-tokens\n// DO NOT EDIT — run npm run build to regenerate\nexport default ${JSON.stringify(tailwindTokens, null, 2)};\n`
);

console.log('✓ babylon-tokens build complete');
console.log('  dist/tokens.css         — CSS custom properties (light :root + dark override)');
console.log('  dist/tailwind.tokens.js — Tailwind config extension');
